##开发环境配置文件
server:
  port: 12320
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.18.107.141:3306/health?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver